### ISSUE TITLE
Password Strength Text

### ISSUE THREAD

**Issue by devercify1** [el-abdel/ngx-pwd-strength#1]
How can I change the language of the password strength text?

If it can't be changed, how can it be hidden?

**Comment by el-abdel** [comment]
hello,

The library use [zxcvbn ](https://github.com/dropbox/zxcvbn) which support only English, I am working on a new release with zxcvbn-ts that supports German, English, Dutch (Belgium) and French and also that can be configrured.

for the moment you can use css to hide the feedback text

**Comment by el-abdel** [comment]
Hi,

I published a new version (1.0.1) of the lib that allow disabling password feedback refere to readme file for more details
